/**
 * FundamentalPanel — dashboard section showing the company's fundamental
 * health, combining a MetricsRadar chart, a metrics table, and a
 * plain-language explanation generated by the LLM.
 *
 * Layout (top to bottom)
 * ──────────────────────
 *   1. Section heading ("Fundamental Analysis")
 *   2. MetricsRadar — visual 5-axis health snapshot
 *   3. Metrics table — raw values for P/E, EPS, P/B, Debt/Equity,
 *                      Profit Margin, Revenue Growth, Dividend Yield
 *   4. Plain-language explanation paragraph (LLM-generated, ≤ 150 words)
 *
 * Props
 * ─────
 *   result       — FundamentalResult from the backend
 *   explanation  — LLM-generated plain-language summary (may be empty string)
 */

import type { FundamentalResult } from '../types'
import MetricsRadar from './charts/MetricsRadar'

// ── Props ─────────────────────────────────────────────────────────────────────

interface FundamentalPanelProps {
  result: FundamentalResult
  explanation: string
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Format a metric value for display.
 * Returns "—" (em-dash) when the value is null so the table never shows
 * "null" or "undefined" to a beginner.
 */
function formatValue(value: number | null, unit: string | null): string {
  if (value === null) return '—'
  const formatted = Number.isInteger(value) ? String(value) : value.toFixed(2)
  return unit ? `${formatted} ${unit}` : formatted
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function FundamentalPanel({ result, explanation }: FundamentalPanelProps) {
  const {
    pe_ratio,
    eps,
    pb_ratio,
    debt_to_equity,
    profit_margin,
    revenue_growth,
    dividend_yield,
    score,
    warnings,
  } = result

  // Build the ordered list of metrics to render in the table.
  const metrics = [pe_ratio, eps, pb_ratio, debt_to_equity, profit_margin, revenue_growth, dividend_yield]

  return (
    <section className="card space-y-5" aria-labelledby="fundamental-heading">
      {/* ── Heading ──────────────────────────────────────────────────────── */}
      <div className="flex items-center justify-between">
        <h2 id="fundamental-heading" className="section-heading mb-0">
          Fundamental Analysis
        </h2>
        <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">
          Score: {score} / 100
        </span>
      </div>

      {/* ── Radar chart ──────────────────────────────────────────────────── */}
      <MetricsRadar
        peRatio={pe_ratio.value}
        pbRatio={pb_ratio.value}
        debtToEquity={debt_to_equity.value}
        profitMargin={profit_margin.value}
        revenueGrowth={revenue_growth.value}
      />

      {/* ── Metrics table ────────────────────────────────────────────────── */}
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-gray-100 text-left text-xs font-semibold uppercase tracking-wide text-gray-400">
              <th className="pb-2 pr-4">Metric</th>
              <th className="pb-2 pr-4">Value</th>
              <th className="pb-2">What it means</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {metrics.map((m) => (
              <tr key={m.label} className="align-top">
                <td className="py-2 pr-4 font-medium text-gray-800 whitespace-nowrap">
                  {m.label}
                </td>
                <td className="py-2 pr-4 tabular-nums text-gray-700 whitespace-nowrap">
                  {formatValue(m.value, m.unit)}
                </td>
                <td className="py-2 text-gray-500">
                  {m.interpretation ?? '—'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ── Plain-language explanation ────────────────────────────────────── */}
      {explanation && (
        <div className="border-t border-gray-100 pt-4 space-y-1">
          <h3 className="text-sm font-semibold text-gray-700">What this means for you</h3>
          <p className="text-sm leading-relaxed text-gray-600">{explanation}</p>
        </div>
      )}

      {/* ── Warning messages (data gaps) ─────────────────────────────────── */}
      {warnings.length > 0 && (
        <ul className="space-y-1">
          {warnings.map((w, i) => (
            <li key={i} className="warning-banner">
              <span aria-hidden="true">⚠</span>
              {w}
            </li>
          ))}
        </ul>
      )}
    </section>
  )
}
