/**
 * TechnicalPanel — dashboard section for technical analysis, containing
 * the PriceChart (close + SMA overlays), VolumeChart, RSIChart, and a
 * plain-language explanation generated by the LLM.
 *
 * Layout (top to bottom)
 * ──────────────────────
 *   1. Section heading ("Technical Analysis") + composite score badge
 *   2. PriceChart — closing price + SMA(20) + SMA(50)
 *   3. VolumeChart — daily volume with up/down colouring
 *   4. RSIChart — RSI(14) with overbought/oversold bands
 *   5. Indicator snapshot — latest values for key indicators
 *   6. Plain-language explanation paragraph (LLM-generated, ≤ 150 words)
 *   7. Warning messages for any missing indicator data
 *
 * Props
 * ─────
 *   result       — TechnicalResult from the backend
 *   explanation  — LLM-generated plain-language summary (may be empty string)
 */

import type { TechnicalResult } from '../types'
import PriceChart from './charts/PriceChart'
import VolumeChart from './charts/VolumeChart'
import RSIChart from './charts/RSIChart'

// ── Props ─────────────────────────────────────────────────────────────────────

interface TechnicalPanelProps {
  result: TechnicalResult
  explanation: string
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Format a nullable number for the indicator snapshot table.
 * Prefix with '$' when `isCurrency` is true.
 */
function fmt(value: number | null, isCurrency = false): string {
  if (value === null) return '—'
  const n = value.toFixed(2)
  return isCurrency ? `$${n}` : n
}

// ── Snapshot row definition ───────────────────────────────────────────────────

interface SnapshotRow {
  label: string
  value: string
  hint: string
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function TechnicalPanel({ result, explanation }: TechnicalPanelProps) {
  const {
    dates,
    close_prices,
    sma_20,
    sma_50,
    rsi_14,
    latest_close,
    latest_rsi,
    latest_macd,
    latest_macd_signal,
    latest_sma_20,
    latest_sma_50,
    latest_sma_200,
    score,
    warnings,
  } = result

  // The backend TechnicalResult does not carry raw volume data.
  // We keep the VolumeChart component available for future use but hide the
  // entire sub-section when there is no data to show — a blank chart with all
  // null bars is not useful to beginners.
  const volumes: (number | null)[] = Array(dates.length).fill(null)
  const hasVolumeData = volumes.some((v) => v !== null)

  const snapshot: SnapshotRow[] = [
    { label: 'Close', value: fmt(latest_close, true), hint: 'Most recent closing price' },
    { label: 'SMA 20', value: fmt(latest_sma_20, true), hint: '20-day moving average' },
    { label: 'SMA 50', value: fmt(latest_sma_50, true), hint: '50-day moving average' },
    { label: 'SMA 200', value: fmt(latest_sma_200, true), hint: '200-day moving average' },
    { label: 'RSI 14', value: fmt(latest_rsi), hint: 'Relative Strength Index (30 = oversold, 70 = overbought)' },
    { label: 'MACD', value: fmt(latest_macd), hint: 'MACD line value' },
    { label: 'MACD Signal', value: fmt(latest_macd_signal), hint: 'MACD signal line value' },
  ]

  return (
    <section className="card space-y-5" aria-labelledby="technical-heading">
      {/* ── Heading ──────────────────────────────────────────────────────── */}
      <div className="flex items-center justify-between">
        <h2 id="technical-heading" className="section-heading mb-0">
          Technical Analysis
        </h2>
        <span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700">
          Score: {score} / 100
        </span>
      </div>

      {/* ── Price chart ──────────────────────────────────────────────────── */}
      <div className="space-y-1">
        <p className="chart-label">Price History</p>
        <PriceChart
          dates={dates}
          closePrices={close_prices}
          sma20={sma_20.values}
          sma50={sma_50.values}
        />
      </div>

      {/* ── Volume chart — only rendered when data is available ──────────── */}
      {hasVolumeData && (
        <div className="space-y-1">
          <p className="text-xs font-medium uppercase tracking-wide text-gray-400">
            Trading Volume
          </p>
          <VolumeChart
            dates={dates}
            volumes={volumes}
            closePrices={close_prices}
          />
        </div>
      )}

      {/* ── RSI chart ────────────────────────────────────────────────────── */}
      <div className="space-y-1">
        <p className="chart-label">RSI (14)</p>
        <RSIChart dates={dates} rsi={rsi_14.values} />
      </div>

      {/* ── Indicator snapshot table ──────────────────────────────────────── */}
      <div className="overflow-x-auto border-t border-gray-100 pt-4">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left text-xs font-semibold uppercase tracking-wide text-gray-400">
              <th className="pb-2 pr-4">Indicator</th>
              <th className="pb-2 pr-4">Latest Value</th>
              <th className="pb-2">Description</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {snapshot.map((row) => (
              <tr key={row.label}>
                <td className="py-2 pr-4 font-medium text-gray-800 whitespace-nowrap">
                  {row.label}
                </td>
                <td className="py-2 pr-4 tabular-nums text-gray-700 whitespace-nowrap">
                  {row.value}
                </td>
                <td className="py-2 text-gray-500">{row.hint}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ── Plain-language explanation ────────────────────────────────────── */}
      {explanation && (
        <div className="border-t border-gray-100 pt-4 space-y-1">
          <h3 className="text-sm font-semibold text-gray-700">What this means for you</h3>
          <p className="text-sm leading-relaxed text-gray-600">{explanation}</p>
        </div>
      )}

      {/* ── Warnings ──────────────────────────────────────────────────────── */}
      {warnings.length > 0 && (
        <ul className="space-y-1">
          {warnings.map((w, i) => (
            <li key={i} className="warning-banner">
              <span aria-hidden="true">⚠</span>
              {w}
            </li>
          ))}
        </ul>
      )}
    </section>
  )
}
