"""
SQLAlchemy ORM table definitions for the Portfolio module (Sub-Task P1).

Four tables are defined here:

    Portfolio         — a named collection of stocks created by the user.
    PortfolioStock    — a single stock entry inside a portfolio, with cached
                        score/recommendation data from the most recent report.
    RankingSnapshot   — an immutable point-in-time ranked list for one portfolio,
                        written on every manual refresh or quarterly scheduler run.
    RankingEntry      — one row per stock inside a ``RankingSnapshot``, holding
                        the full score breakdown captured at snapshot time.

Design notes
────────────
- All primary keys are UUID strings generated by the application layer (not the
  DB), so IDs are portable across environments and never collide when importing.
- ``RankingSnapshot`` and its ``RankingEntry`` children are immutable once
  written — never updated, only inserted and (via cascade) deleted.
- ``PortfolioStock.overall_score`` is the *only* sub-score cached on the stock
  row; it is sufficient for the live ranking sort. The three sub-scores
  (fundamental, technical, sentiment) are stored in ``RankingEntry`` rows so
  historical snapshots preserve the full breakdown.
- SQLite requires ``check_same_thread=False`` on the engine (set in
  ``database.py``); this module is engine-agnostic.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, relationship


# ── Declarative base ──────────────────────────────────────────────────────────


class Base(DeclarativeBase):
    """Shared declarative base for all portfolio ORM models."""


# ── Portfolio ─────────────────────────────────────────────────────────────────


class Portfolio(Base):
    """
    A named collection of stocks created and managed by the user.

    Each portfolio owns zero or more ``PortfolioStock`` entries and accumulates
    ``RankingSnapshot`` history over time.  Deleting a portfolio cascades to
    all child stocks and snapshots.
    """

    __tablename__ = "portfolios"

    id: str = Column(String, primary_key=True)
    """UUID string — generated by ``uuid4()`` in the application layer."""

    name: str = Column(String(120), nullable=False)
    """
    Human-readable portfolio name chosen by the user.

    Maximum 120 characters; must not be blank (enforced by the Pydantic schema).
    """

    description: str = Column(Text, default="")
    """
    Optional free-text description of the portfolio's purpose or strategy.

    Defaults to an empty string when the user leaves it blank.
    """

    created_at: datetime = Column(DateTime, default=datetime.utcnow)
    """UTC datetime when this portfolio row was first inserted."""

    updated_at: datetime = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow
    )
    """
    UTC datetime of the most recent update to this row.

    Automatically refreshed by SQLAlchemy whenever the row is modified via the
    ORM (``onupdate`` hook).
    """

    # ── Relationships ─────────────────────────────────────────────────────────

    stocks = relationship(
        "PortfolioStock",
        back_populates="portfolio",
        cascade="all, delete-orphan",
    )
    """All ``PortfolioStock`` entries belonging to this portfolio."""

    ranking_snaps = relationship(
        "RankingSnapshot",
        back_populates="portfolio",
        cascade="all, delete-orphan",
    )
    """All ``RankingSnapshot`` rows ever created for this portfolio."""


# ── PortfolioStock ────────────────────────────────────────────────────────────


class PortfolioStock(Base):
    """
    A single stock entry inside a portfolio.

    Stores cached report data (score, recommendation, summary) so the portfolio
    ranking page renders without hitting the in-memory job store.  These values
    are refreshed whenever ``crud.update_stock_from_report()`` is called —
    either after a manual "Add to Portfolio" action or after a quarterly refresh.
    """

    __tablename__ = "portfolio_stocks"
    __table_args__ = (
        UniqueConstraint("portfolio_id", "ticker", name="uq_portfolio_ticker"),
    )

    id: str = Column(String, primary_key=True)
    """UUID string — generated by ``uuid4()`` in the application layer."""

    portfolio_id: str = Column(
        String, ForeignKey("portfolios.id"), nullable=False
    )
    """Foreign key referencing the owning ``Portfolio.id``."""

    ticker: str = Column(String(10), nullable=False)
    """
    Upper-case ticker symbol (e.g. ``"AAPL"``).

    Maximum 10 characters; validated against the ticker regex in the API schema.
    Together with ``portfolio_id`` this forms a unique pair (see ``UniqueConstraint``).
    """

    company_name: str = Column(String(200), default="")
    """
    Full company name copied from the report payload (e.g. ``"Apple Inc."``).

    Displayed in the portfolio ranking table.  Defaults to empty string until
    the first report is linked.
    """

    short_summary: str = Column(Text, default="")
    """
    Executive summary copied from the most recent completed report.

    Sourced from ``ReportPayload.executive_summary``.  Used as a quick
    one-line tooltip in the portfolio UI.  Defaults to empty string.
    """

    latest_report_id: str | None = Column(String, nullable=True)
    """
    Job ID (UUID string) of the most recently linked completed report.

    Points into the in-memory ``JobStore``; this reference becomes stale after
    a server restart (the job store is ephemeral).  The Report page handles
    that case with a "Report expired — regenerate" call-to-action.
    ``None`` until the first report is linked.
    """

    overall_score: float | None = Column(Float, nullable=True)
    """
    Composite overall score (0–100) from the most recent report.

    Computed as ``fundamental_score × 0.40 + technical_score × 0.40
    + sentiment_score × 0.20``.  Used as the primary sort key for live
    portfolio ranking.  ``None`` when data could not be fetched for this stock.
    """

    recommendation: str | None = Column(String(10), nullable=True)
    """
    Investment recommendation copied from the most recent report.

    One of ``"Buy"``, ``"Hold"``, or ``"Sell"``.
    ``None`` until the first report is linked.
    """

    added_at: datetime = Column(DateTime, default=datetime.utcnow)
    """UTC datetime when this stock was first added to the portfolio."""

    last_refreshed: datetime | None = Column(DateTime, nullable=True)
    """
    UTC datetime of the most recent successful score update.

    Set by ``crud.update_stock_from_report()``.  ``None`` until the first
    report data is written back to this row.
    """

    # ── Relationships ─────────────────────────────────────────────────────────

    portfolio = relationship("Portfolio", back_populates="stocks")
    """The parent ``Portfolio`` that owns this stock entry."""


# ── RankingSnapshot ───────────────────────────────────────────────────────────


class RankingSnapshot(Base):
    """
    An immutable point-in-time ranking of all stocks in one portfolio.

    Written once by ``crud.save_ranking_snapshot()`` and never updated.
    Every manual refresh and every quarterly scheduler run produces a new row.
    The full historical series of snapshots is exposed by
    ``GET /api/portfolios/{id}/history``.
    """

    __tablename__ = "ranking_snapshots"

    id: str = Column(String, primary_key=True)
    """UUID string — generated by ``uuid4()`` in the application layer."""

    portfolio_id: str = Column(
        String, ForeignKey("portfolios.id"), nullable=False
    )
    """Foreign key referencing the owning ``Portfolio.id``."""

    snapshot_at: datetime = Column(DateTime, nullable=False)
    """UTC datetime when this snapshot was created (set to ``datetime.utcnow()`` on insert)."""

    trigger: str = Column(String(20), default="manual")
    """
    What caused this snapshot to be written.

    One of:
      ``"manual"``    — user clicked "Refresh Now" on the portfolio detail page.
      ``"quarterly"`` — the APScheduler quarterly cron job fired automatically.
    """

    # ── Relationships ─────────────────────────────────────────────────────────

    entries = relationship(
        "RankingEntry",
        back_populates="snapshot",
        cascade="all, delete-orphan",
        order_by="RankingEntry.rank",
    )
    """
    All ``RankingEntry`` rows for this snapshot, ordered ascending by ``rank``.
    """

    portfolio = relationship("Portfolio", back_populates="ranking_snaps")
    """The parent ``Portfolio`` this snapshot belongs to."""


# ── RankingEntry ──────────────────────────────────────────────────────────────


class RankingEntry(Base):
    """
    One ranked stock row inside a ``RankingSnapshot``.

    Captures the full score breakdown (overall + three sub-scores) at the
    moment the snapshot was written, allowing historical views to show *why*
    a stock's rank changed between quarters.
    """

    __tablename__ = "ranking_entries"

    id: str = Column(String, primary_key=True)
    """UUID string — generated by ``uuid4()`` in the application layer."""

    snapshot_id: str = Column(
        String, ForeignKey("ranking_snapshots.id"), nullable=False
    )
    """Foreign key referencing the parent ``RankingSnapshot.id``."""

    rank: int = Column(Integer, nullable=False)
    """
    1-based position in the ranking (rank 1 = highest ``overall_score``).

    Equal scores are broken alphabetically by ``ticker`` (ascending) to ensure
    a stable, deterministic ordering.  Stocks with ``overall_score = null``
    are placed at the bottom of the ranking.
    """

    ticker: str = Column(String(10), nullable=False)
    """Upper-case ticker symbol (e.g. ``"MSFT"``) at the time of snapshot."""

    overall_score: float | None = Column(Float, nullable=True)
    """
    Composite overall score (0–100) recorded at snapshot time.

    ``None`` when data was unavailable for this stock during the refresh that
    produced this snapshot.
    """

    fundamental_score: float | None = Column(Float, nullable=True)
    """
    Fundamental analysis sub-score (0–100) recorded at snapshot time.

    Sourced from ``ReportPayload.fundamental_result.score``.
    ``None`` when the fundamental analyser could not produce a score.
    """

    technical_score: float | None = Column(Float, nullable=True)
    """
    Technical analysis sub-score (0–100) recorded at snapshot time.

    Sourced from ``ReportPayload.technical_result.score``.
    ``None`` when the technical analyser could not produce a score.
    """

    sentiment_score: float | None = Column(Float, nullable=True)
    """
    News sentiment sub-score (0–100) recorded at snapshot time.

    Sourced from ``ReportPayload.sentiment_result.score``.
    ``None`` when no news headlines were available for this stock.
    """

    recommendation: str | None = Column(String(10), nullable=True)
    """
    Investment recommendation recorded at snapshot time.

    One of ``"Buy"``, ``"Hold"``, or ``"Sell"``.  Derived from
    ``overall_score`` using the same thresholds as the live report
    (≥ 60 → Buy, 40–59 → Hold, < 40 → Sell).
    ``None`` when ``overall_score`` is ``None``.
    """

    # ── Relationships ─────────────────────────────────────────────────────────

    snapshot = relationship("RankingSnapshot", back_populates="entries")
    """The parent ``RankingSnapshot`` this entry belongs to."""
